        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:10:38 2016
        MODULE DSBESSEK0__genmod
          INTERFACE 
            FUNCTION DSBESSEK0(X)
              REAL(KIND=8) :: X
              REAL(KIND=8) :: DSBESSEK0
            END FUNCTION DSBESSEK0
          END INTERFACE 
        END MODULE DSBESSEK0__genmod
