        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:10:38 2016
        MODULE DSBESSEI1__genmod
          INTERFACE 
            FUNCTION DSBESSEI1(X)
              REAL(KIND=8) :: X
              REAL(KIND=8) :: DSBESSEI1
            END FUNCTION DSBESSEI1
          END INTERFACE 
        END MODULE DSBESSEI1__genmod
