        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:10:39 2016
        MODULE DSBESSEK1__genmod
          INTERFACE 
            FUNCTION DSBESSEK1(X)
              REAL(KIND=8) :: X
              REAL(KIND=8) :: DSBESSEK1
            END FUNCTION DSBESSEK1
          END INTERFACE 
        END MODULE DSBESSEK1__genmod
