        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:10:40 2016
        MODULE DSHIPRECINT3__genmod
          INTERFACE 
            SUBROUTINE DSHIPRECINT3(FUN,LOWLIM,UPPLIM,RESULT)
              EXTERNAL FUN
              REAL(KIND=8) :: LOWLIM
              REAL(KIND=8) :: UPPLIM
              REAL(KIND=8) :: RESULT
            END SUBROUTINE DSHIPRECINT3
          END INTERFACE 
        END MODULE DSHIPRECINT3__genmod
