        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:10:46 2016
        MODULE DSLNPOISINT__genmod
          INTERFACE 
            FUNCTION DSLNPOISINT(COUNTS_TOT,COUNTS_SIG,OBSCOUNTS,ERRORSQ&
     &,LOGNORMAL)
              REAL(KIND=8) :: COUNTS_TOT
              REAL(KIND=8) :: COUNTS_SIG
              INTEGER(KIND=4) :: OBSCOUNTS
              REAL(KIND=8) :: ERRORSQ
              LOGICAL(KIND=4) :: LOGNORMAL
              REAL(KIND=8) :: DSLNPOISINT
            END FUNCTION DSLNPOISINT
          END INTERFACE 
        END MODULE DSLNPOISINT__genmod
