        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:10:44 2016
        MODULE DSWRITE__genmod
          INTERFACE 
            SUBROUTINE DSWRITE(LEVEL,OPT,MESSAGE)
              INTEGER(KIND=4) :: LEVEL
              INTEGER(KIND=4) :: OPT
              CHARACTER(*) :: MESSAGE
            END SUBROUTINE DSWRITE
          END INTERFACE 
        END MODULE DSWRITE__genmod
