        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:10:48 2016
        MODULE LAMBERTWLN__genmod
          INTERFACE 
            FUNCTION LAMBERTWLN(LNX)
              REAL(KIND=8) :: LNX
              REAL(KIND=8) :: LAMBERTWLN
            END FUNCTION LAMBERTWLN
          END INTERFACE 
        END MODULE LAMBERTWLN__genmod
