        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:10:37 2016
        MODULE XGETUA__genmod
          INTERFACE 
            SUBROUTINE XGETUA(IUNITA,N)
              INTEGER(KIND=4) :: IUNITA(5)
              INTEGER(KIND=4) :: N
            END SUBROUTINE XGETUA
          END INTERFACE 
        END MODULE XGETUA__genmod
