        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:10:52 2016
        MODULE DMHAINIT__genmod
          INTERFACE 
            SUBROUTINE DMHAINIT(YIELDK)
              INTEGER(KIND=4) :: YIELDK
            END SUBROUTINE DMHAINIT
          END INTERFACE 
        END MODULE DMHAINIT__genmod
