        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:10:50 2016
        MODULE DMHADYDTH__genmod
          INTERFACE 
            FUNCTION DMHADYDTH(CTH)
              REAL(KIND=8) :: CTH
              REAL(KIND=8) :: DMHADYDTH
            END FUNCTION DMHADYDTH
          END INTERFACE 
        END MODULE DMHADYDTH__genmod
