        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:10:56 2016
        MODULE DMHAYIELDS__genmod
          INTERFACE 
            FUNCTION DMHAYIELDS(EH,EMUTH,HNO,YIELDK,ISTAT)
              REAL(KIND=8) :: EH
              REAL(KIND=8) :: EMUTH
              INTEGER(KIND=4) :: HNO
              INTEGER(KIND=4) :: YIELDK
              INTEGER(KIND=4) :: ISTAT
              REAL(KIND=8) :: DMHAYIELDS
            END FUNCTION DMHAYIELDS
          END INTERFACE 
        END MODULE DMHAYIELDS__genmod
