        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:10:52 2016
        MODULE DMHAIFIND__genmod
          INTERFACE 
            SUBROUTINE DMHAIFIND(VALUE,ARRAY,IPL,II,IMIN,IMAX)
              INTEGER(KIND=4) :: IMAX
              INTEGER(KIND=4) :: IMIN
              REAL(KIND=8) :: VALUE
              REAL(KIND=8) :: ARRAY(IMIN+10:IMAX+11)
              REAL(KIND=8) :: IPL
              INTEGER(KIND=4) :: II
            END SUBROUTINE DMHAIFIND
          END INTERFACE 
        END MODULE DMHAIFIND__genmod
