        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:10:52 2016
        MODULE DMHALOYIELD__genmod
          INTERFACE 
            FUNCTION DMHALOYIELD(EGEV,YIELDK,ISTAT)
              REAL(KIND=8) :: EGEV
              INTEGER(KIND=4) :: YIELDK
              INTEGER(KIND=4) :: ISTAT
              REAL(KIND=8) :: DMHALOYIELD
            END FUNCTION DMHALOYIELD
          END INTERFACE 
        END MODULE DMHALOYIELD__genmod
