        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:10:53 2016
        MODULE DMHAYIELDDEC__genmod
          INTERFACE 
            FUNCTION DMHAYIELDDEC(EH,HNO,EMUTH,YIELDK,ISTAT)
              REAL(KIND=8) :: EH
              INTEGER(KIND=4) :: HNO
              REAL(KIND=8) :: EMUTH
              INTEGER(KIND=4) :: YIELDK
              INTEGER(KIND=4) :: ISTAT
              REAL(KIND=8) :: DMHAYIELDDEC
            END FUNCTION DMHAYIELDDEC
          END INTERFACE 
        END MODULE DMHAYIELDDEC__genmod
