        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:10:50 2016
        MODULE DMHADEC__genmod
          INTERFACE 
            SUBROUTINE DMHADEC(YIELDK,FLTYP,FI)
              INTEGER(KIND=4) :: YIELDK
              INTEGER(KIND=4) :: FLTYP
              INTEGER(KIND=4) :: FI
            END SUBROUTINE DMHADEC
          END INTERFACE 
        END MODULE DMHADEC__genmod
