        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:10:55 2016
        MODULE DMHAYIELDS2__genmod
          INTERFACE 
            FUNCTION DMHAYIELDS2(EH,EMUTH,HNO,YIELDK,ISTAT)
              REAL(KIND=8) :: EH
              REAL(KIND=8) :: EMUTH
              INTEGER(KIND=4) :: HNO
              INTEGER(KIND=4) :: YIELDK
              INTEGER(KIND=4) :: ISTAT
              REAL(KIND=8) :: DMHAYIELDS2
            END FUNCTION DMHAYIELDS2
          END INTERFACE 
        END MODULE DMHAYIELDS2__genmod
