        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:06 2016
        MODULE DMHASETUP__genmod
          INTERFACE 
            SUBROUTINE DMHASETUP
            END SUBROUTINE DMHASETUP
          END INTERFACE 
        END MODULE DMHASETUP__genmod
