        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:09 2016
        MODULE DMHRGALSUSY__genmod
          INTERFACE 
            SUBROUTINE DMHRGALSUSY(GAGARATE,GAZRATE)
              REAL(KIND=8) :: GAGARATE
              REAL(KIND=8) :: GAZRATE
            END SUBROUTINE DMHRGALSUSY
          END INTERFACE 
        END MODULE DMHRGALSUSY__genmod
