        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:07 2016
        MODULE DMHRGACDIFFSUSY__genmod
          INTERFACE 
            FUNCTION DMHRGACDIFFSUSY(EGAM,ISTAT)
              REAL(KIND=8) :: EGAM
              INTEGER(KIND=4) :: ISTAT
              REAL(KIND=8) :: DMHRGACDIFFSUSY
            END FUNCTION DMHRGACDIFFSUSY
          END INTERFACE 
        END MODULE DMHRGACDIFFSUSY__genmod
