        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:08 2016
        MODULE DMHRGACONTDIFF__genmod
          INTERFACE 
            FUNCTION DMHRGACONTDIFF(EGAM,JPSI,ISTAT)
              REAL(KIND=8) :: EGAM
              REAL(KIND=8) :: JPSI
              INTEGER(KIND=4) :: ISTAT
              REAL(KIND=8) :: DMHRGACONTDIFF
            END FUNCTION DMHRGACONTDIFF
          END INTERFACE 
        END MODULE DMHRGACONTDIFF__genmod
