        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:08 2016
        MODULE DMHRGACSUSY__genmod
          INTERFACE 
            FUNCTION DMHRGACSUSY(EGATH,ISTAT)
              REAL(KIND=8) :: EGATH
              INTEGER(KIND=4) :: ISTAT
              REAL(KIND=8) :: DMHRGACSUSY
            END FUNCTION DMHRGACSUSY
          END INTERFACE 
        END MODULE DMHRGACSUSY__genmod
