        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:06 2016
        MODULE DSHALOYIELDDB__genmod
          INTERFACE 
            FUNCTION DSHALOYIELDDB(EGEV,YIELDK,ISTAT)
              REAL(KIND=8) :: EGEV
              INTEGER(KIND=4) :: YIELDK
              INTEGER(KIND=4) :: ISTAT
              REAL(KIND=8) :: DSHALOYIELDDB
            END FUNCTION DSHALOYIELDDB
          END INTERFACE 
        END MODULE DSHALOYIELDDB__genmod
