        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:08 2016
        MODULE DSHRGALINE__genmod
          INTERFACE 
            SUBROUTINE DSHRGALINE(JPSI,GAGA,GAZ)
              REAL(KIND=8) :: JPSI
              REAL(KIND=8) :: GAGA
              REAL(KIND=8) :: GAZ
            END SUBROUTINE DSHRGALINE
          END INTERFACE 
        END MODULE DSHRGALINE__genmod
