        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:07 2016
        MODULE DSHRDBDIFF0__genmod
          INTERFACE 
            FUNCTION DSHRDBDIFF0(TD,SOLARMOD,HOW)
              REAL(KIND=8) :: TD
              INTEGER(KIND=4) :: SOLARMOD
              INTEGER(KIND=4) :: HOW
              REAL(KIND=8) :: DSHRDBDIFF0
            END FUNCTION DSHRDBDIFF0
          END INTERFACE 
        END MODULE DSHRDBDIFF0__genmod
