        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:07 2016
        MODULE DSHRDBARDIFF__genmod
          INTERFACE 
            FUNCTION DSHRDBARDIFF(TD,SOLARMOD,HOW)
              REAL(KIND=8) :: TD
              INTEGER(KIND=4) :: SOLARMOD
              INTEGER(KIND=4) :: HOW
              REAL(KIND=8) :: DSHRDBARDIFF
            END FUNCTION DSHRDBARDIFF
          END INTERFACE 
        END MODULE DSHRDBARDIFF__genmod
