        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:09 2016
        MODULE DSHRPBARDIFF__genmod
          INTERFACE 
            FUNCTION DSHRPBARDIFF(TP,SOLARMOD,HOW)
              REAL(KIND=8) :: TP
              INTEGER(KIND=4) :: SOLARMOD
              INTEGER(KIND=4) :: HOW
              REAL(KIND=8) :: DSHRPBARDIFF
            END FUNCTION DSHRPBARDIFF
          END INTERFACE 
        END MODULE DSHRPBARDIFF__genmod
