        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:10 2016
        MODULE DSNSIGVGACDIFF__genmod
          INTERFACE 
            SUBROUTINE DSNSIGVGACDIFF(EGA,NSIGVGACDIFF)
              REAL(KIND=8) :: EGA
              REAL(KIND=8) :: NSIGVGACDIFF
            END SUBROUTINE DSNSIGVGACDIFF
          END INTERFACE 
        END MODULE DSNSIGVGACDIFF__genmod
