        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:10 2016
        MODULE DSNSIGVGACONT__genmod
          INTERFACE 
            SUBROUTINE DSNSIGVGACONT(EGATH,NSIGVGACONT)
              REAL(KIND=8) :: EGATH
              REAL(KIND=8) :: NSIGVGACONT
            END SUBROUTINE DSNSIGVGACONT
          END INTERFACE 
        END MODULE DSNSIGVGACONT__genmod
