        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:11 2016
        MODULE DSNSIGVGALINE__genmod
          INTERFACE 
            SUBROUTINE DSNSIGVGALINE(NSIGVGAGA,NSIGVGAZ)
              REAL(KIND=8) :: NSIGVGAGA
              REAL(KIND=8) :: NSIGVGAZ
            END SUBROUTINE DSNSIGVGALINE
          END INTERFACE 
        END MODULE DSNSIGVGALINE__genmod
