        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:22 2016
        MODULE DMIBYIELDONE__genmod
          INTERFACE 
            FUNCTION DMIBYIELDONE(EMUTHR,IBCH,YIELDK,ISTAT)
              REAL(KIND=8) :: EMUTHR
              INTEGER(KIND=4) :: IBCH
              INTEGER(KIND=4) :: YIELDK
              INTEGER(KIND=4) :: ISTAT
              REAL(KIND=8) :: DMIBYIELDONE
            END FUNCTION DMIBYIELDONE
          END INTERFACE 
        END MODULE DMIBYIELDONE__genmod
