        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:16 2016
        MODULE DMIBSELECT__genmod
          INTERFACE 
            SUBROUTINE DMIBSELECT
            END SUBROUTINE DMIBSELECT
          END INTERFACE 
        END MODULE DMIBSELECT__genmod
