        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:22 2016
        MODULE DMIBYIELD_FSR__genmod
          INTERFACE 
            FUNCTION DMIBYIELD_FSR(EGEV,YIELDK,ISTAT)
              REAL(KIND=8) :: EGEV
              INTEGER(KIND=4) :: YIELDK
              INTEGER(KIND=4) :: ISTAT
              REAL(KIND=8) :: DMIBYIELD_FSR
            END FUNCTION DMIBYIELD_FSR
          END INTERFACE 
        END MODULE DMIBYIELD_FSR__genmod
