        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:23 2016
        MODULE DMIBYIELDONE_FSR__genmod
          INTERFACE 
            FUNCTION DMIBYIELDONE_FSR(MWIMP,EMUTHR,FSRCH,YIELDK,ISTAT)
              REAL(KIND=8) :: MWIMP
              REAL(KIND=8) :: EMUTHR
              INTEGER(KIND=4) :: FSRCH
              INTEGER(KIND=4) :: YIELDK
              INTEGER(KIND=4) :: ISTAT
              REAL(KIND=8) :: DMIBYIELDONE_FSR
            END FUNCTION DMIBYIELDONE_FSR
          END INTERFACE 
        END MODULE DMIBYIELDONE_FSR__genmod
