        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:23 2016
        MODULE DMIBYIELD_USER__genmod
          INTERFACE 
            FUNCTION DMIBYIELD_USER(EGEV,YIELDK,ISTAT)
              REAL(KIND=8) :: EGEV
              REAL(KIND=8) :: YIELDK
              INTEGER(KIND=4) :: ISTAT
              REAL(KIND=8) :: DMIBYIELD_USER
            END FUNCTION DMIBYIELD_USER
          END INTERFACE 
        END MODULE DMIBYIELD_USER__genmod
