        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:15 2016
        MODULE DMIBINTSEL2__genmod
          INTERFACE 
            FUNCTION DMIBINTSEL2(XINT)
              REAL(KIND=8) :: XINT
              REAL(KIND=8) :: DMIBINTSEL2
            END FUNCTION DMIBINTSEL2
          END INTERFACE 
        END MODULE DMIBINTSEL2__genmod
