        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:02 2016
        MODULE DMHMNUMRHO__genmod
          INTERFACE 
            FUNCTION DMHMNUMRHO(RADIALDIST)
              REAL(KIND=8) :: RADIALDIST
              REAL(KIND=8) :: DMHMNUMRHO
            END FUNCTION DMHMNUMRHO
          END INTERFACE 
        END MODULE DMHMNUMRHO__genmod
