        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:10:57 2016
        MODULE DMHMAXIPROB__genmod
          INTERFACE 
            FUNCTION DMHMAXIPROB(RADCOORD,VERTCOORD)
              REAL(KIND=8) :: RADCOORD
              REAL(KIND=8) :: VERTCOORD
              REAL(KIND=8) :: DMHMAXIPROB
            END FUNCTION DMHMAXIPROB
          END INTERFACE 
        END MODULE DMHMAXIPROB__genmod
