        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:00 2016
        MODULE DMHMJAVEPAR2__genmod
          INTERFACE 
            FUNCTION DMHMJAVEPAR2(COSPSI)
              REAL(KIND=8) :: COSPSI
              REAL(KIND=8) :: DMHMJAVEPAR2
            END FUNCTION DMHMJAVEPAR2
          END INTERFACE 
        END MODULE DMHMJAVEPAR2__genmod
