        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:03 2016
        MODULE DMHMSPHRHO__genmod
          INTERFACE 
            FUNCTION DMHMSPHRHO(RADIALDIST)
              REAL(KIND=8) :: RADIALDIST
              REAL(KIND=8) :: DMHMSPHRHO
            END FUNCTION DMHMSPHRHO
          END INTERFACE 
        END MODULE DMHMSPHRHO__genmod
