        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:00 2016
        MODULE DMHMJAVEPAR1__genmod
          INTERFACE 
            FUNCTION DMHMJAVEPAR1(RRTMP)
              REAL(KIND=8) :: RRTMP
              REAL(KIND=8) :: DMHMJAVEPAR1
            END FUNCTION DMHMJAVEPAR1
          END INTERFACE 
        END MODULE DMHMJAVEPAR1__genmod
