        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:10:59 2016
        MODULE DMHMJAVE__genmod
          INTERFACE 
            FUNCTION DMHMJAVE(COSPSI0IN,DELTAIN)
              REAL(KIND=8) :: COSPSI0IN
              REAL(KIND=8) :: DELTAIN
              REAL(KIND=8) :: DMHMJAVE
            END FUNCTION DMHMJAVE
          END INTERFACE 
        END MODULE DMHMJAVE__genmod
