        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:10:58 2016
        MODULE DMHMBURRHO__genmod
          INTERFACE 
            FUNCTION DMHMBURRHO(RADIALDIST)
              REAL(KIND=8) :: RADIALDIST
              REAL(KIND=8) :: DMHMBURRHO
            END FUNCTION DMHMBURRHO
          END INTERFACE 
        END MODULE DMHMBURRHO__genmod
