        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:02 2016
        MODULE DMHMN03RHO__genmod
          INTERFACE 
            FUNCTION DMHMN03RHO(RADIALDIST)
              REAL(KIND=8) :: RADIALDIST
              REAL(KIND=8) :: DMHMN03RHO
            END FUNCTION DMHMN03RHO
          END INTERFACE 
        END MODULE DMHMN03RHO__genmod
