        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:10:57 2016
        MODULE DMHMABGRHO__genmod
          INTERFACE 
            FUNCTION DMHMABGRHO(RADIALDIST)
              REAL(KIND=8) :: RADIALDIST
              REAL(KIND=8) :: DMHMABGRHO
            END FUNCTION DMHMABGRHO
          END INTERFACE 
        END MODULE DMHMABGRHO__genmod
