        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:01 2016
        MODULE DSHMJAVEPAR4__genmod
          INTERFACE 
            FUNCTION DSHMJAVEPAR4(RRIN)
              REAL(KIND=8) :: RRIN
              REAL(KIND=8) :: DSHMJAVEPAR4
            END FUNCTION DSHMJAVEPAR4
          END INTERFACE 
        END MODULE DSHMJAVEPAR4__genmod
