        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:00 2016
        MODULE DSHMJAVEPAR3__genmod
          INTERFACE 
            FUNCTION DSHMJAVEPAR3(COSPSIIN)
              REAL(KIND=8) :: COSPSIIN
              REAL(KIND=8) :: DSHMJAVEPAR3
            END FUNCTION DSHMJAVEPAR3
          END INTERFACE 
        END MODULE DSHMJAVEPAR3__genmod
