        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:10:58 2016
        MODULE DSHMBOERRHOAXI__genmod
          INTERFACE 
            FUNCTION DSHMBOERRHOAXI(R,Z,HOW)
              REAL(KIND=8) :: R
              REAL(KIND=8) :: Z
              INTEGER(KIND=4) :: HOW
              REAL(KIND=8) :: DSHMBOERRHOAXI
            END FUNCTION DSHMBOERRHOAXI
          END INTERFACE 
        END MODULE DSHMBOERRHOAXI__genmod
