        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:03 2016
        MODULE DSHMRHO2CYLINT__genmod
          INTERFACE 
            FUNCTION DSHMRHO2CYLINT(RMAX,ZMAX)
              REAL(KIND=8) :: RMAX
              REAL(KIND=8) :: ZMAX
              REAL(KIND=8) :: DSHMRHO2CYLINT
            END FUNCTION DSHMRHO2CYLINT
          END INTERFACE 
        END MODULE DSHMRHO2CYLINT__genmod
