        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:10:59 2016
        MODULE DSHMDFISOTRNUM__genmod
          INTERFACE 
            FUNCTION DSHMDFISOTRNUM(V)
              REAL(KIND=8) :: V
              REAL(KIND=8) :: DSHMDFISOTRNUM
            END FUNCTION DSHMDFISOTRNUM
          END INTERFACE 
        END MODULE DSHMDFISOTRNUM__genmod
