        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:00 2016
        MODULE DSHMJAVEGC__genmod
          INTERFACE 
            FUNCTION DSHMJAVEGC(COSPSI0IN,DELTAIN)
              REAL(KIND=8) :: COSPSI0IN
              REAL(KIND=8) :: DELTAIN
              REAL(KIND=8) :: DSHMJAVEGC
            END FUNCTION DSHMJAVEGC
          END INTERFACE 
        END MODULE DSHMJAVEGC__genmod
