        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:04 2016
        MODULE DSHMUDFEARTH__genmod
          INTERFACE 
            FUNCTION DSHMUDFEARTH(U)
              REAL(KIND=8) :: U
              REAL(KIND=8) :: DSHMUDFEARTH
            END FUNCTION DSHMUDFEARTH
          END INTERFACE 
        END MODULE DSHMUDFEARTH__genmod
