        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:10:57 2016
        MODULE DSHMAXIRHO__genmod
          INTERFACE 
            FUNCTION DSHMAXIRHO(RADCOORD,VERTCOORD)
              REAL(KIND=8) :: RADCOORD
              REAL(KIND=8) :: VERTCOORD
              REAL(KIND=8) :: DSHMAXIRHO
            END FUNCTION DSHMAXIRHO
          END INTERFACE 
        END MODULE DSHMAXIRHO__genmod
