        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:10:59 2016
        MODULE DSHMHALOPROF__genmod
          INTERFACE 
            SUBROUTINE DSHMHALOPROF(RR,VAL)
              REAL(KIND=8) :: RR
              REAL(KIND=8) :: VAL
            END SUBROUTINE DSHMHALOPROF
          END INTERFACE 
        END MODULE DSHMHALOPROF__genmod
