        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:05 2016
        MODULE DSHMUDFNUMCINT__genmod
          INTERFACE 
            FUNCTION DSHMUDFNUMCINT(X)
              REAL(KIND=8) :: X
              REAL(KIND=8) :: DSHMUDFNUMCINT
            END FUNCTION DSHMUDFNUMCINT
          END INTERFACE 
        END MODULE DSHMUDFNUMCINT__genmod
