        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:01 2016
        MODULE DSHMJAVEPAR5__genmod
          INTERFACE 
            FUNCTION DSHMJAVEPAR5(RRIN)
              REAL(KIND=8) :: RRIN
              REAL(KIND=8) :: DSHMJAVEPAR5
            END FUNCTION DSHMJAVEPAR5
          END INTERFACE 
        END MODULE DSHMJAVEPAR5__genmod
