        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:04 2016
        MODULE DSHMUDFEARTHTAB__genmod
          INTERFACE 
            FUNCTION DSHMUDFEARTHTAB(U,TYPE)
              REAL(KIND=8) :: U
              INTEGER(KIND=4) :: TYPE
              REAL(KIND=8) :: DSHMUDFEARTHTAB
            END FUNCTION DSHMUDFEARTHTAB
          END INTERFACE 
        END MODULE DSHMUDFEARTHTAB__genmod
