        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:04 2016
        MODULE DSHMUDFGAUSS__genmod
          INTERFACE 
            FUNCTION DSHMUDFGAUSS(U)
              REAL(KIND=8) :: U
              REAL(KIND=8) :: DSHMUDFGAUSS
            END FUNCTION DSHMUDFGAUSS
          END INTERFACE 
        END MODULE DSHMUDFGAUSS__genmod
