        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:06 2016
        MODULE DSHMVELEARTH__genmod
          INTERFACE 
            SUBROUTINE DSHMVELEARTH(TDAYS)
              REAL(KIND=8) :: TDAYS
            END SUBROUTINE DSHMVELEARTH
          END INTERFACE 
        END MODULE DSHMVELEARTH__genmod
