        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:05 2016
        MODULE DSHMUDFISO__genmod
          INTERFACE 
            FUNCTION DSHMUDFISO(U)
              REAL(KIND=8) :: U
              REAL(KIND=8) :: DSHMUDFISO
            END FUNCTION DSHMUDFISO
          END INTERFACE 
        END MODULE DSHMUDFISO__genmod
