clear;
gclim=[0 1e31];
redf = 0.75;
bflw = 2.5;
bfsize = 25;
lab_fontsize = 24/redf; axes_fontsize = 24/redf; names_fontsize = 10/redf;  cbar_fontsize = 16/redf;  textbox_fontsize = 30/redf; twolines_fontsize = 30/redf;exp_fontsize = 14/redf;  
 l1='-k'; lw1=0.8; lwaxes = 2.0;
 lwdd= 3.0; 
 l2='.r'; lw1=1.2; 
figure
subplot(    4,    2,    1);
set(gcf, 'NextPlot', 'replacechildren');
box on; axis square; hold on;
bestfit = [    0.60794E+02 0.0];
mean = [    0.68366E+02, 0.0];
refpoint = [    0.33800E+02 0.0];
tmp = load (fullfile('../../plot_data/bb_sim_rec/','bb_sim_rec_p1.dat'));
x = tmp(:,1);
pdf = tmp(:,2);
hbar = bar(x,pdf);
set(hbar, 'EdgeColor', 'b','FaceColor', [0.4 0.8 1.0],'BarWidth', 1.0);
colormap(cool); hold on;
 text('String','m_\chi (GeV)','FontSize',lab_fontsize, 'Units', 'normalized', 'Position', [0.5 -0.18], 'HorizontalAlignment', 'center');
ylabel('Probability', 'FontSize',lab_fontsize);
axis tight;
set(gca,'YLim', [0.0 1.1]);
set(gca,'Layer','top','FontSize',axes_fontsize,  'LineWidth', lwaxes);
set(gca,'ticklength',2*get(gca,'ticklength'));
plot(bestfit(1), bestfit(2),'x','MarkerSize',bfsize,'MarkerEdgeColor','k', 'LineWidth', bflw/redf);
plot(bestfit(1), bestfit(2),'o','MarkerSize',bfsize,'MarkerFaceColor', 'none', 'MarkerEdgeColor','k', 'LineWidth', bflw/redf);
plot(mean(1), mean(2),'o','MarkerSize',bfsize/2,'MarkerFaceColor','k', 'MarkerEdgeColor','k', 'LineWidth', bflw/redf*0.75);
plot(refpoint(1), refpoint(2),'d','MarkerSize',8,'MarkerFaceColor','r', 'MarkerEdgeColor','y', 'LineWidth', 2.0);
set(gcf,'paperpositionmode','auto');
set(gcf, 'Units','centimeters');
set(gcf, 'Position',[ 0.0 0.0 16.5 16.5]);
set(gca, 'Units','centimeters');
set(gca,'position',[4.0 4.0 11.0 11.0]);
set(gcf, 'PaperUnits','centimeters');
set(gcf, 'PaperSize',[16.5 16.5]);
hold off;
print -dpsc2 -loose  ../../output_files/bb_sim_rec/bb_sim_rec_1D_1.ps;
figure
subplot(    4,    2,    2);
set(gcf, 'NextPlot', 'replacechildren');
box on; axis square; hold on;
bestfit = [    0.21381E+01 0.0];
mean = [    0.22004E+01, 0.0];
refpoint = [    0.27520E+01 0.0];
tmp = load (fullfile('../../plot_data/bb_sim_rec/','bb_sim_rec_p2.dat'));
x = tmp(:,1);
pdf = tmp(:,2);
hbar = bar(x,pdf);
set(hbar, 'EdgeColor', 'b','FaceColor', [0.4 0.8 1.0],'BarWidth', 1.0);
colormap(cool); hold on;
 text('String','log[<\sigma v> (10^{27} cm^3 s^{-1})]','FontSize',lab_fontsize, 'Units', 'normalized', 'Position', [0.5 -0.18], 'HorizontalAlignment', 'center');
ylabel('Probability', 'FontSize',lab_fontsize);
axis tight;
set(gca,'YLim', [0.0 1.1]);
set(gca,'Layer','top','FontSize',axes_fontsize,  'LineWidth', lwaxes);
set(gca,'ticklength',2*get(gca,'ticklength'));
plot(bestfit(1), bestfit(2),'x','MarkerSize',bfsize,'MarkerEdgeColor','k', 'LineWidth', bflw/redf);
plot(bestfit(1), bestfit(2),'o','MarkerSize',bfsize,'MarkerFaceColor', 'none', 'MarkerEdgeColor','k', 'LineWidth', bflw/redf);
plot(mean(1), mean(2),'o','MarkerSize',bfsize/2,'MarkerFaceColor','k', 'MarkerEdgeColor','k', 'LineWidth', bflw/redf*0.75);
plot(refpoint(1), refpoint(2),'d','MarkerSize',8,'MarkerFaceColor','r', 'MarkerEdgeColor','y', 'LineWidth', 2.0);
set(gcf,'paperpositionmode','auto');
set(gcf, 'Units','centimeters');
set(gcf, 'Position',[ 0.0 0.0 16.5 16.5]);
set(gca, 'Units','centimeters');
set(gca,'position',[4.0 4.0 11.0 11.0]);
set(gcf, 'PaperUnits','centimeters');
set(gcf, 'PaperSize',[16.5 16.5]);
hold off;
print -dpsc2 -loose  ../../output_files/bb_sim_rec/bb_sim_rec_1D_2.ps;
figure
subplot(    4,    2,    3);
set(gcf, 'NextPlot', 'replacechildren');
box on; axis square; hold on;
bestfit = [    0.11080E-02 0.0];
mean = [    0.70206E-01, 0.0];
refpoint = [    0.92400E+00 0.0];
tmp = load (fullfile('../../plot_data/bb_sim_rec/','bb_sim_rec_p3.dat'));
x = tmp(:,1);
pdf = tmp(:,2);
hbar = bar(x,pdf);
set(hbar, 'EdgeColor', 'b','FaceColor', [0.4 0.8 1.0],'BarWidth', 1.0);
colormap(cool); hold on;
 text('String','BR_{b \bar{b}}','FontSize',lab_fontsize, 'Units', 'normalized', 'Position', [0.5 -0.18], 'HorizontalAlignment', 'center');
ylabel('Probability', 'FontSize',lab_fontsize);
axis tight;
set(gca,'YLim', [0.0 1.1]);
set(gca,'Layer','top','FontSize',axes_fontsize,  'LineWidth', lwaxes);
set(gca,'ticklength',2*get(gca,'ticklength'));
plot(bestfit(1), bestfit(2),'x','MarkerSize',bfsize,'MarkerEdgeColor','k', 'LineWidth', bflw/redf);
plot(bestfit(1), bestfit(2),'o','MarkerSize',bfsize,'MarkerFaceColor', 'none', 'MarkerEdgeColor','k', 'LineWidth', bflw/redf);
plot(mean(1), mean(2),'o','MarkerSize',bfsize/2,'MarkerFaceColor','k', 'MarkerEdgeColor','k', 'LineWidth', bflw/redf*0.75);
plot(refpoint(1), refpoint(2),'d','MarkerSize',8,'MarkerFaceColor','r', 'MarkerEdgeColor','y', 'LineWidth', 2.0);
set(gcf,'paperpositionmode','auto');
set(gcf, 'Units','centimeters');
set(gcf, 'Position',[ 0.0 0.0 16.5 16.5]);
set(gca, 'Units','centimeters');
set(gca,'position',[4.0 4.0 11.0 11.0]);
set(gcf, 'PaperUnits','centimeters');
set(gcf, 'PaperSize',[16.5 16.5]);
hold off;
print -dpsc2 -loose  ../../output_files/bb_sim_rec/bb_sim_rec_1D_3.ps;
figure
subplot(    4,    2,    4);
set(gcf, 'NextPlot', 'replacechildren');
box on; axis square; hold on;
bestfit = [    0.32231E-01 0.0];
mean = [    0.95309E-01, 0.0];
refpoint = [   -0.40000E+01 0.0];
tmp = load (fullfile('../../plot_data/bb_sim_rec/','bb_sim_rec_p7.dat'));
x = tmp(:,1);
pdf = tmp(:,2);
hbar = bar(x,pdf);
set(hbar, 'EdgeColor', 'b','FaceColor', [0.4 0.8 1.0],'BarWidth', 1.0);
colormap(cool); hold on;
 text('String','BR_{e^+ e^-}','FontSize',lab_fontsize, 'Units', 'normalized', 'Position', [0.5 -0.18], 'HorizontalAlignment', 'center');
ylabel('Probability', 'FontSize',lab_fontsize);
axis tight;
set(gca,'YLim', [0.0 1.1]);
set(gca,'Layer','top','FontSize',axes_fontsize,  'LineWidth', lwaxes);
set(gca,'ticklength',2*get(gca,'ticklength'));
plot(bestfit(1), bestfit(2),'x','MarkerSize',bfsize,'MarkerEdgeColor','k', 'LineWidth', bflw/redf);
plot(bestfit(1), bestfit(2),'o','MarkerSize',bfsize,'MarkerFaceColor', 'none', 'MarkerEdgeColor','k', 'LineWidth', bflw/redf);
plot(mean(1), mean(2),'o','MarkerSize',bfsize/2,'MarkerFaceColor','k', 'MarkerEdgeColor','k', 'LineWidth', bflw/redf*0.75);
plot(refpoint(1), refpoint(2),'d','MarkerSize',8,'MarkerFaceColor','r', 'MarkerEdgeColor','y', 'LineWidth', 2.0);
set(gcf,'paperpositionmode','auto');
set(gcf, 'Units','centimeters');
set(gcf, 'Position',[ 0.0 0.0 16.5 16.5]);
set(gca, 'Units','centimeters');
set(gca,'position',[4.0 4.0 11.0 11.0]);
set(gcf, 'PaperUnits','centimeters');
set(gcf, 'PaperSize',[16.5 16.5]);
hold off;
print -dpsc2 -loose  ../../output_files/bb_sim_rec/bb_sim_rec_1D_4.ps;
figure
subplot(    4,    2,    5);
set(gcf, 'NextPlot', 'replacechildren');
box on; axis square; hold on;
bestfit = [    0.93130E-02 0.0];
mean = [    0.54049E-01, 0.0];
refpoint = [   -0.40000E+01 0.0];
tmp = load (fullfile('../../plot_data/bb_sim_rec/','bb_sim_rec_p8.dat'));
x = tmp(:,1);
pdf = tmp(:,2);
hbar = bar(x,pdf);
set(hbar, 'EdgeColor', 'b','FaceColor', [0.4 0.8 1.0],'BarWidth', 1.0);
colormap(cool); hold on;
 text('String','BR_{\mu^+ \mu^-}','FontSize',lab_fontsize, 'Units', 'normalized', 'Position', [0.5 -0.18], 'HorizontalAlignment', 'center');
ylabel('Probability', 'FontSize',lab_fontsize);
axis tight;
set(gca,'YLim', [0.0 1.1]);
set(gca,'Layer','top','FontSize',axes_fontsize,  'LineWidth', lwaxes);
set(gca,'ticklength',2*get(gca,'ticklength'));
plot(bestfit(1), bestfit(2),'x','MarkerSize',bfsize,'MarkerEdgeColor','k', 'LineWidth', bflw/redf);
plot(bestfit(1), bestfit(2),'o','MarkerSize',bfsize,'MarkerFaceColor', 'none', 'MarkerEdgeColor','k', 'LineWidth', bflw/redf);
plot(mean(1), mean(2),'o','MarkerSize',bfsize/2,'MarkerFaceColor','k', 'MarkerEdgeColor','k', 'LineWidth', bflw/redf*0.75);
plot(refpoint(1), refpoint(2),'d','MarkerSize',8,'MarkerFaceColor','r', 'MarkerEdgeColor','y', 'LineWidth', 2.0);
set(gcf,'paperpositionmode','auto');
set(gcf, 'Units','centimeters');
set(gcf, 'Position',[ 0.0 0.0 16.5 16.5]);
set(gca, 'Units','centimeters');
set(gca,'position',[4.0 4.0 11.0 11.0]);
set(gcf, 'PaperUnits','centimeters');
set(gcf, 'PaperSize',[16.5 16.5]);
hold off;
print -dpsc2 -loose  ../../output_files/bb_sim_rec/bb_sim_rec_1D_5.ps;
figure
subplot(    4,    2,    6);
set(gcf, 'NextPlot', 'replacechildren');
box on; axis square; hold on;
bestfit = [    0.26285E+00 0.0];
mean = [    0.20611E+00, 0.0];
refpoint = [   -0.40000E+01 0.0];
tmp = load (fullfile('../../plot_data/bb_sim_rec/','bb_sim_rec_p9.dat'));
x = tmp(:,1);
pdf = tmp(:,2);
hbar = bar(x,pdf);
set(hbar, 'EdgeColor', 'b','FaceColor', [0.4 0.8 1.0],'BarWidth', 1.0);
colormap(cool); hold on;
 text('String','BR_{c \bar{c}}','FontSize',lab_fontsize, 'Units', 'normalized', 'Position', [0.5 -0.18], 'HorizontalAlignment', 'center');
ylabel('Probability', 'FontSize',lab_fontsize);
axis tight;
set(gca,'YLim', [0.0 1.1]);
set(gca,'Layer','top','FontSize',axes_fontsize,  'LineWidth', lwaxes);
set(gca,'ticklength',2*get(gca,'ticklength'));
plot(bestfit(1), bestfit(2),'x','MarkerSize',bfsize,'MarkerEdgeColor','k', 'LineWidth', bflw/redf);
plot(bestfit(1), bestfit(2),'o','MarkerSize',bfsize,'MarkerFaceColor', 'none', 'MarkerEdgeColor','k', 'LineWidth', bflw/redf);
plot(mean(1), mean(2),'o','MarkerSize',bfsize/2,'MarkerFaceColor','k', 'MarkerEdgeColor','k', 'LineWidth', bflw/redf*0.75);
plot(refpoint(1), refpoint(2),'d','MarkerSize',8,'MarkerFaceColor','r', 'MarkerEdgeColor','y', 'LineWidth', 2.0);
set(gcf,'paperpositionmode','auto');
set(gcf, 'Units','centimeters');
set(gcf, 'Position',[ 0.0 0.0 16.5 16.5]);
set(gca, 'Units','centimeters');
set(gca,'position',[4.0 4.0 11.0 11.0]);
set(gcf, 'PaperUnits','centimeters');
set(gcf, 'PaperSize',[16.5 16.5]);
hold off;
print -dpsc2 -loose  ../../output_files/bb_sim_rec/bb_sim_rec_1D_6.ps;
figure
subplot(    4,    2,    7);
set(gcf, 'NextPlot', 'replacechildren');
box on; axis square; hold on;
bestfit = [    0.52602E-04 0.0];
mean = [    0.11281E-01, 0.0];
refpoint = [   -0.40000E+01 0.0];
tmp = load (fullfile('../../plot_data/bb_sim_rec/','bb_sim_rec_p10.dat'));
x = tmp(:,1);
pdf = tmp(:,2);
hbar = bar(x,pdf);
set(hbar, 'EdgeColor', 'b','FaceColor', [0.4 0.8 1.0],'BarWidth', 1.0);
colormap(cool); hold on;
 text('String','BR_{g g}','FontSize',lab_fontsize, 'Units', 'normalized', 'Position', [0.5 -0.18], 'HorizontalAlignment', 'center');
ylabel('Probability', 'FontSize',lab_fontsize);
axis tight;
set(gca,'YLim', [0.0 1.1]);
set(gca,'Layer','top','FontSize',axes_fontsize,  'LineWidth', lwaxes);
set(gca,'ticklength',2*get(gca,'ticklength'));
plot(bestfit(1), bestfit(2),'x','MarkerSize',bfsize,'MarkerEdgeColor','k', 'LineWidth', bflw/redf);
plot(bestfit(1), bestfit(2),'o','MarkerSize',bfsize,'MarkerFaceColor', 'none', 'MarkerEdgeColor','k', 'LineWidth', bflw/redf);
plot(mean(1), mean(2),'o','MarkerSize',bfsize/2,'MarkerFaceColor','k', 'MarkerEdgeColor','k', 'LineWidth', bflw/redf*0.75);
plot(refpoint(1), refpoint(2),'d','MarkerSize',8,'MarkerFaceColor','r', 'MarkerEdgeColor','y', 'LineWidth', 2.0);
set(gcf,'paperpositionmode','auto');
set(gcf, 'Units','centimeters');
set(gcf, 'Position',[ 0.0 0.0 16.5 16.5]);
set(gca, 'Units','centimeters');
set(gca,'position',[4.0 4.0 11.0 11.0]);
set(gcf, 'PaperUnits','centimeters');
set(gcf, 'PaperSize',[16.5 16.5]);
hold off;
print -dpsc2 -loose  ../../output_files/bb_sim_rec/bb_sim_rec_1D_7.ps;
figure
subplot(    4,    2,    8);
set(gcf, 'NextPlot', 'replacechildren');
box on; axis square; hold on;
bestfit = [    0.69444E+00 0.0];
mean = [    0.56304E+00, 0.0];
refpoint = [    0.76000E-01 0.0];
tmp = load (fullfile('../../plot_data/bb_sim_rec/','bb_sim_rec_p20.dat'));
x = tmp(:,1);
pdf = tmp(:,2);
hbar = bar(x,pdf);
set(hbar, 'EdgeColor', 'b','FaceColor', [0.4 0.8 1.0],'BarWidth', 1.0);
colormap(cool); hold on;
 text('String','BR_{\tau^+\tau^-}','FontSize',lab_fontsize, 'Units', 'normalized', 'Position', [0.5 -0.18], 'HorizontalAlignment', 'center');
ylabel('Probability', 'FontSize',lab_fontsize);
axis tight;
set(gca,'YLim', [0.0 1.1]);
set(gca,'Layer','top','FontSize',axes_fontsize,  'LineWidth', lwaxes);
set(gca,'ticklength',2*get(gca,'ticklength'));
plot(bestfit(1), bestfit(2),'x','MarkerSize',bfsize,'MarkerEdgeColor','k', 'LineWidth', bflw/redf);
plot(bestfit(1), bestfit(2),'o','MarkerSize',bfsize,'MarkerFaceColor', 'none', 'MarkerEdgeColor','k', 'LineWidth', bflw/redf);
plot(mean(1), mean(2),'o','MarkerSize',bfsize/2,'MarkerFaceColor','k', 'MarkerEdgeColor','k', 'LineWidth', bflw/redf*0.75);
plot(refpoint(1), refpoint(2),'d','MarkerSize',8,'MarkerFaceColor','r', 'MarkerEdgeColor','y', 'LineWidth', 2.0);
set(gcf,'paperpositionmode','auto');
set(gcf, 'Units','centimeters');
set(gcf, 'Position',[ 0.0 0.0 16.5 16.5]);
set(gca, 'Units','centimeters');
set(gca,'position',[4.0 4.0 11.0 11.0]);
set(gcf, 'PaperUnits','centimeters');
set(gcf, 'PaperSize',[16.5 16.5]);
hold off;
print -dpsc2 -loose  ../../output_files/bb_sim_rec/bb_sim_rec_1D_8.ps;
