        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:25 2016
        MODULE DSREADPAR__genmod
          INTERFACE 
            SUBROUTINE DSREADPAR(UNIT)
              INTEGER(KIND=4) :: UNIT
            END SUBROUTINE DSREADPAR
          END INTERFACE 
        END MODULE DSREADPAR__genmod
