        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:31 2016
        MODULE DARKMATTER__genmod
          INTERFACE 
            SUBROUTINE DARKMATTER(FLAG,INP,INN,DMINOUT)
              USE PARAMETERS
              TYPE (FLAGS), INTENT(IN) :: FLAG
              TYPE (INPUT_PARAMS), INTENT(IN) :: INP
              TYPE (NUISANCE_PARAMS), INTENT(IN) :: INN
              TYPE (DM), INTENT(INOUT) :: DMINOUT
            END SUBROUTINE DARKMATTER
          END INTERFACE 
        END MODULE DARKMATTER__genmod
