        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:31 2016
        MODULE DMINIT__genmod
          INTERFACE 
            SUBROUTINE DMINIT(INP,INN,DMIN)
              USE PARAMETERS
              TYPE (INPUT_PARAMS), INTENT(IN) :: INP
              TYPE (NUISANCE_PARAMS), INTENT(IN) :: INN
              TYPE (DM), INTENT(IN) :: DMIN
            END SUBROUTINE DMINIT
          END INTERFACE 
        END MODULE DMINIT__genmod
