        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:33 2016
        MODULE SIGIP_EXP__genmod
          INTERFACE 
            SUBROUTINE SIGIP_EXP(MCHI,SIGIP_BOUND,EXPERIMENT)
              REAL(KIND=8), INTENT(IN) :: MCHI
              REAL(KIND=8), INTENT(OUT) :: SIGIP_BOUND
              INTEGER(KIND=4), INTENT(IN) :: EXPERIMENT
            END SUBROUTINE SIGIP_EXP
          END INTERFACE 
        END MODULE SIGIP_EXP__genmod
