        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep 16 16:11:32 2016
        MODULE TIMESTAMP__genmod
          INTERFACE 
            SUBROUTINE TIMESTAMP
            END SUBROUTINE TIMESTAMP
          END INTERFACE 
        END MODULE TIMESTAMP__genmod
